<a href="https://colab.research.google.com/github/Omdevkar67/Data_Science_Lab/blob/main/Experiment03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Determinant of matrix without Numpy
print("Enter the elements of the 3x3 matrix row-wise:")

matrix = []

for i in range(3):
    row = list(map(int, input(f"Enter row {i+1}: ").split()))
    matrix.append(row)

a, b, c = matrix[0]
d, e, f = matrix[1]
g, h, i = matrix[2]

determinant = a*(e*i - f*h) - b*(d*i - f*g) + c*(d*h - e*g)

print("\nDeterminant of the matrix:")
print(determinant)



Enter the elements of the 3x3 matrix row-wise:
Enter row 1: 3 2 5
Enter row 2: 7 6 2
Enter row 3: 1 9 5 

Determinant of the matrix:
255


In [ ]:
#Determinant of matrix using Numpy
import numpy as np

print("Enter the elements of 3x3 matrix row-wise:")

elements = []

for i in range(3):
    row = list(map(int, input(f"Enter row {i+1} (elements separated by space): ").split()))
    elements.append(row)

matrix = np.array(elements)

determinant = np.linalg.det(matrix)

print("\nMatrix:")
print(matrix)

print("\nDeterminant of the given matrix is:")
print(determinant)



Enter the elements of 3x3 matrix row-wise:
Enter row 1 (elements separated by space): 3 2 5
Enter row 2 (elements separated by space): 7 6 2
Enter row 3 (elements separated by space): 1 9 5

Matrix:
[[3 2 5]
 [7 6 2]
 [1 9 5]]

Determinant of the given matrix is:
254.99999999999991


In [ ]:
#Inverse of the matrix without using Numpy
print("Enter the elements of the 3x3 matrix row-wise:")

matrix = []

for i in range(3):
    row = list(map(int, input(f"Enter row {i+1}: ").split()))
    matrix.append(row)

a, b, c = matrix[0]
d, e, f = matrix[1]
g, h, i = matrix[2]

det = a*(e*i - f*h) - b*(d*i - f*g) + c*(d*h - e*g)

print("\nDeterminant of the matrix:")
print(det)

if det == 0:
    print("Inverse of this matrix does not exist")
else:
    inverse = [
        [(e*i - f*h)/det, (c*h - b*i)/det, (b*f - c*e)/det],
        [(f*g - d*i)/det, (a*i - c*g)/det, (c*d - a*f)/det],
        [(d*h - e*g)/det, (b*g - a*h)/det, (a*e - b*d)/det]
    ]

    print("\nInverse of the matrix is:")
    for row in inverse:
        print(row)



Enter the elements of the 3x3 matrix row-wise:
Enter row 1: 2 6 3
Enter row 2: 2 6 2
Enter row 3: 2 5 8

Determinant of the matrix:
-2

Inverse of the matrix is:
[-19.0, 16.5, 3.0]
[6.0, -5.0, -1.0]
[1.0, -1.0, -0.0]


In [ ]:
#Inverse of matrix using Numpy
import numpy as np

print("Enter elements of 3x3 matrix:")

A = []

for i in range(3):
    row = []
    for j in range(3):
        value = float(input(f"a[{i+1}][{j+1}]: "))
        row.append(value)
    A.append(row)

A = np.array(A)

print("\nInverse of the matrix:")
print(np.linalg.inv(A))

Enter elements of 3x3 matrix:
a[1][1]: 2
a[1][2]: 6
a[1][3]: 3
a[2][1]: 2
a[2][2]: 6
a[2][3]: 2
a[3][1]: 2
a[3][2]: 5
a[3][3]: 8

Inverse of the matrix:
[[-19.   16.5   3. ]
 [  6.   -5.   -1. ]
 [  1.   -1.   -0. ]]


In [ ]:
print("Solve the system:")
print("a1*x + b1*y = c1")
print("a2*x + b2*y = c2")

a1 = float(input("Enter a1: "))
b1 = float(input("Enter b1: "))
c1 = float(input("Enter c1: "))

a2 = float(input("Enter a2: "))
b2 = float(input("Enter b2: "))
c2 = float(input("Enter c2: "))

# Determinant
D = a1*b2 - a2*b1

if D == 0:
    print("\nThe system has no unique solution (Determinant is zero).")
else:
    Dx = c1*b2 - c2*b1
    Dy = a1*c2 - a2*c1

    x = Dx / D
    y = Dy / D

    print("\nSolution of the system:")
    print("x =", x)
    print("y =", y)

Solve the system:
a1*x + b1*y = c1
a2*x + b2*y = c2
Enter a1: 2
Enter b1: 5
Enter c1: 10
Enter a2: 2
Enter b2: 6
Enter c2: 9

Solution of the system:
x = 7.5
y = -1.0


In [ ]:
#Solve a system of 2 Linear Equations using Numpy
import numpy as np

print("Solve the system:")
print("a1*x + b1*y = c1")
print("a2*x + b2*y = c2")

# Input values
a1 = float(input("Enter a1: "))
b1 = float(input("Enter b1: "))
c1 = float(input("Enter c1: "))

a2 = float(input("Enter a2: "))
b2 = float(input("Enter b2: "))
c2 = float(input("Enter c2: "))

# Create coefficient matrix A
A = np.array([[a1, b1],
              [a2, b2]])

# Create constant matrix B
B = np.array([c1, c2])

# Check determinant
det = np.linalg.det(A)

if det == 0:
    print("\nThe system has no unique solution (Determinant is zero).")
else:
    solution = np.linalg.solve(A,B)
    print("\nSolution of the system:")
    print("x =", solution[0])
    print("y =", solution[1])





Solve the system:
a1*x + b1*y = c1
a2*x + b2*y = c2
Enter a1: 2
Enter b1: 5
Enter c1: 10
Enter a2: 2
Enter b2: 6
Enter c2: 9

Solution of the system:
x = 7.5
y = -1.0
